### ISSUE TITLE
Javascript and Svelte starter kit - error 404

### ISSUE THREAD

**Issue by Smartmind12** [NativeScript/docs#115]
When a user clicks Javascript or Svelte online starter on https://docs.nativescript.org/setup/ & on https://docs.nativescript.org/guide/creating-a-project then an error 404 is thrown.

I would like to rectify this error so that the documentation's usability increases.

![Screenshot 2023-10-21 at 8 21 28 PM](https://github.com/NativeScript/docs-v8/assets/91927689/8a4cb0e8-90f7-41ea-9fbc-8ab5bc170ccb)
![Screenshot 2023-10-21 at 8 28 09 PM](https://github.com/NativeScript/docs-v8/assets/91927689/9c62e212-b88b-48fe-86c9-2864669d4adc)

**Comment by rigor789** [comment]
Thanks, fixed the redirect.

https://nativescript.new/js should be working now.
