### ISSUE TITLE
Error in page preview in stackblitz

### ISSUE THREAD

**Issue by vallemar** [NativeScript/docs#125]
When I try to modify a page in stackblitz I cannot see the preview, the error is the following

![image](https://github.com/NativeScript/docs/assets/15719383/b7c08fae-69f9-40cc-a733-7512ed6b1ca3)

**Comment by rigor789** [comment]
Should work now... GitHub releases urls don't allow CORS requests (super weird?!) so had to proxy them... https://github.com/NativeScript/docs/blob/main/functions/__/vitepress-theme.tgz.ts
